#!/usr/bin/env bash

set -e # abort on errors

export MUMBLE_PROTOC="/usr/lib/mxe/usr/x86_64-unknown-linux-gnu/bin/protoc"
export PATH="${PATH}:/usr/lib/mxe/usr/bin"

cd "${HOME}"
git clone --recurse-submodules --depth=1 "${MUMBLE_SOURCE}"
cd -

mkdir -p "${HOME}/mumble/3rdparty/asio"
mv -T "${HOME}/ASIOSDK2.3" "/home/user/mumble/3rdparty/asio"

cd "${HOME}/mumble"
"${BIN_ARCH}-w64-mingw32.static-qmake-qt5" -recursive CONFIG+="release g15-emulator no-overlay no-bonjour no-elevation no-ice"
make
cd -

cp -r "${HOME}/mumble/release" "${HOME}/result"

# run given command
${*}
